project:
  type: website
  output-dir: docs
  resources:
    - files/*

from: markdown+raw_html

website:
  title: "Vanessa Quintana"
  navbar:
    background: primary
    foreground: light
    pinned: true
    left:
      - href: modeling_basics.qmd
        text: Modeling Basics    
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Models
      - href: cv.qmd
        text: CV
      - text: News
        menu:
          - text: "2026"
            href: news/2026.qmd
    right:
      - icon: github
        href: https://github.com/vmahan1998
      - icon: envelope
        href: mailto:vanessa.mahan@maine.edu
      - icon: linkedin
        href: https://www.linkedin.com/in/vanessa-mahan/
  page-footer:
    left: "© 2026 Vanessa Mahan"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: [flatly, custom.scss]
    css: styles.css
    toc: true
    toc-depth: 2
    page-layout: article

execute:
  freeze: auto